In [0]:
pip install -q kaggle


In [3]:
from google.colab import files

files.upload()
! mkdir ~/.kaggle

! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

Saving kaggle.json to kaggle.json
mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [4]:
!kaggle datasets download -d cosmos98/twitter-and-reddit-sentimental-analysis-dataset
!mkdir Dataset
! unzip /content/twitter-and-reddit-sentimental-analysis-dataset.zip

 90% 9.00M/10.0M [00:01<00:00, 6.96MB/s]
100% 10.0M/10.0M [00:01<00:00, 8.00MB/s]
mkdir: cannot create directory ‘Dataset’: File exists
Archive:  /content/twitter-and-reddit-sentimental-analysis-dataset.zip
  inflating: Reddit_Data.csv         
  inflating: Twitter_Data.csv        


In [0]:
import pandas as pd 
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [0]:
df=pd.read_csv("Reddit_Data.csv")

In [7]:
df.head()

clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [0]:
comments=df['clean_comment']

In [9]:
type(comments)

pandas.core.series.Series

In [0]:
comments=list(comments)

In [11]:
type(comments)

list

In [12]:
comments[:5]

[' family mormon have never tried explain them they still stare puzzled from time time like some kind strange creature nonetheless they have come admire for the patience calmness equanimity acceptance and compassion have developed all the things buddhism teaches ',
 'buddhism has very much lot compatible with christianity especially considering that sin and suffering are almost the same thing suffering caused wanting things shouldn want going about getting things the wrong way christian this would mean wanting things that don coincide with god will and wanting things that coincide but without the aid jesus buddhism could also seen proof god all mighty will and omnipotence certainly christians are lucky have one such christ there side but what about everyone else well many christians believe god grace salvation and buddhism god way showing grace upon others would also help study the things jesus said and see how buddha has made similar claims such rich man getting into heaven joke basic

In [0]:
labels=df['category']

In [0]:
labels=list(labels)

In [0]:
train_comments=comments[:30000]
train_labels=labels[:30000]
val_comments=comments[30000:]
val_labels=labels[30000:]

In [0]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [0]:

embedding_dim = 25

trunc_type='post'
padding_type='post'
oov_tok = "<OOV>"
training_size = 35000

In [0]:
tokenizer=Tokenizer(oov_token=oov_tok)

In [0]:
for i in range(0,len(train_comments)):
  if type(train_comments[i])==float:
    train_comments.pop(i)
    train_labels.pop(i)




In [199]:
tokenizer.fit_on_texts(train_comments)
total_words=len(tokenizer.word_index)+1
print(total_words)

49851


In [0]:
train_seq=tokenizer.texts_to_sequences(train_comments)

In [201]:
max_seq_len=max([len(x) for x in train_seq])
max_seq_len

1307

In [0]:
padded_train=pad_sequences(train_seq,maxlen=25,padding=padding_type, truncating=trunc_type)

In [0]:
padded_train=np.array(padded_train)

In [239]:
padded_train[:3]

array([[  286, 25042,    11,   120,   640,   834,    42,    10,    93,
        11148, 14878,    24,    54,    54,    23,    44,   292,  4150,
        14879,  7743,    10,    11,   129,  3069,     6],
       [ 1406,    21,    75,    74,    82,  7226,    12,  2840,   456,
         1162,     4,  6357,     3,  1872,     8,   374,     2,    41,
           90,  1872,  1791,  2663,   112,   952,    91],
       [  488,    40,   103,    90,   116,    20,    10,   204,    46,
           78,    86,  2046,   834,  1241,    16,   821,     3,    10,
            8,  9964,    72,   137,   360,    17,     7]], dtype=int32)

In [243]:
padded_train[:3]

array([[  286, 25042,    11,   120,   640,   834,    42,    10,    93,
        11148, 14878,    24,    54,    54,    23,    44,   292,  4150,
        14879,  7743,    10,    11,   129,  3069,     6],
       [ 1406,    21,    75,    74,    82,  7226,    12,  2840,   456,
         1162,     4,  6357,     3,  1872,     8,   374,     2,    41,
           90,  1872,  1791,  2663,   112,   952,    91],
       [  488,    40,   103,    90,   116,    20,    10,   204,    46,
           78,    86,  2046,   834,  1241,    16,   821,     3,    10,
            8,  9964,    72,   137,   360,    17,     7]], dtype=int32)

In [244]:
print(len(padded_train))
print(len(train_labels))

29917
29917


In [0]:
for i in range(0,len(val_comments)):
  if type(val_comments[i])==float:
    val_comments.pop(i)
    val_labels.pop(i)

In [0]:
test_seq=tokenizer.texts_to_sequences(val_comments)

In [0]:
padded_test=pad_sequences(test_seq,maxlen=25,padding=padding_type, truncating=trunc_type)

In [0]:
padded_test=np.array(padded_test)

In [249]:
padded_test[:3]


array([[   20,     2,    16,   199,    11,   688,   347,    27,    91,
          103,    78,   802,    12,    37,   286,   316,    37,   157,
         8485,  7718,     3,     1,     3,   347,   278],
       [    9,   176,   160,    21,  1074,    68,   231,     4,   102,
          691,   803,   183,     1,     1,     2,    41,    83,  4697,
           33,   633,   411,   142,   130,    33,  5038],
       [  580,    57,   187,    36,   119,   566,   441,    97,    16,
           23, 17714,   901, 10979,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0]], dtype=int32)

In [250]:
print(len(padded_test))
print(len(val_labels))

7232
7232


In [251]:
print(len(train_comments))
print(len(train_labels))

29917
29917


In [252]:
print(len(val_comments))
print(len(val_labels))

7232
7232


In [0]:
train_labels=np.array(train_labels)
val_labels=np.array(val_labels)

In [254]:
train_labels[:3]

array([ 1,  1, -1])

In [0]:

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional,GlobalAveragePooling1D,Flatten,Conv1D,GRU,GlobalMaxPooling1D
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers
import tensorflow.keras.utils as ku 
import numpy as np
import tensorflow_hub as hub

In [345]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=25))
model.add(Bidirectional(LSTM(50, return_sequences = True)))

model.add(Dense(36, activation='relu'))
model.add(Flatten())
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_41"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_38 (Embedding)     (None, 25, 100)           4985100   
_________________________________________________________________
bidirectional_14 (Bidirectio (None, 25, 100)           60400     
_________________________________________________________________
dense_80 (Dense)             (None, 25, 36)            3636      
_________________________________________________________________
flatten_9 (Flatten)          (None, 900)               0         
_________________________________________________________________
dense_81 (Dense)             (None, 3)                 2703      
Total params: 5,051,839
Trainable params: 5,051,839
Non-trainable params: 0
_________________________________________________________________
None


In [346]:
model.summary()

Model: "sequential_41"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_38 (Embedding)     (None, 25, 100)           4985100   
_________________________________________________________________
bidirectional_14 (Bidirectio (None, 25, 100)           60400     
_________________________________________________________________
dense_80 (Dense)             (None, 25, 36)            3636      
_________________________________________________________________
flatten_9 (Flatten)          (None, 900)               0         
_________________________________________________________________
dense_81 (Dense)             (None, 3)                 2703      
Total params: 5,051,839
Trainable params: 5,051,839
Non-trainable params: 0
_________________________________________________________________


In [0]:
import tensorflow.keras.utils as ku 

In [348]:
train_label = ku.to_categorical(train_labels, num_classes=3)
val_label = ku.to_categorical(val_labels, num_classes=3)

print(train_label[:3])

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [349]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('accuracy')>0.93):
      print("\nReached 93% accuracy so cancelling training!")
      self.model.stop_training = True


reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2,
                              patience=5, min_lr=1e-6)

num_epochs = 30
history = model.fit(padded_train,train_label, epochs=num_epochs, validation_data=(padded_test,val_label),callbacks=[reduce_lr,myCallback()])

Epoch 1/30
935/935 [==============================] - 50s 54ms/step - loss: 0.5506 - accuracy: 0.7718 - val_loss: 0.3053 - val_accuracy: 0.8855 - lr: 0.0010
Epoch 2/30
935/935 [==============================] - 50s 53ms/step - loss: 0.2278 - accuracy: 0.9163 - val_loss: 0.3335 - val_accuracy: 0.8782 - lr: 0.0010
Epoch 3/30
935/935 [==============================] - ETA: 0s - loss: 0.1176 - accuracy: 0.9589
Reached 93% accuracy so cancelling training!
935/935 [==============================] - 50s 53ms/step - loss: 0.1176 - accuracy: 0.9589 - val_loss: 0.3618 - val_accuracy: 0.8786 - lr: 0.0010


In [350]:
model.save('drive/My Drive/RedditSentiment/version5')

INFO:tensorflow:Assets written to: drive/My Drive/RedditSentiment/version5/assets


INFO:tensorflow:Assets written to: drive/My Drive/RedditSentiment/version5/assets


In [0]:
seed_text=["worst movie ever","Amazing match ,well done bruh","samosa","Avengers Endgame made me cry","I loved this match","I hate You","I hate you though cannot deny how important you are to me "]

In [0]:
seed=tokenizer.texts_to_sequences(seed_text)

In [0]:
seed_pad=pad_sequences(seed,maxlen=25,padding=padding_type, truncating=trunc_type)

In [384]:
print(seed_pad)

[[  808   172   235     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0]
 [  738  1164    76   163  9779     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0]
 [    1     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0]
 [17277  7242   133     1  1815     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0]
 [    1  1908     5  1164     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0]
 [    1   214     7     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0]
 [    1   214     7   211   359  2724    34   319     7   

In [385]:
ref={
    0:'Neutral',
    1:'Positive',
    2:'Negative'
}

prediction=model.predict(seed_pad)
for x in prediction :
  print(ref[np.argmax(x)])
  

Negative
Positive
Neutral
Neutral
Positive
Negative
Negative
